#region Streamlit Intro Section
import streamlit as st

# Using unsafe_allow_html=True so we can style the header and sections with HTML/CSS.
# This is safe here because all text is static and controlled by us (no user input).
st.markdown("""
<h1 style='text-align: center; color: #6B4D31;'>🍀 Health Guru AI: Your Ayurvedic Remedies Assistant</h1>

<p style='text-align: center; font-size: 18px;'>
Welcome to your personal Ayurvedic companion — helping you discover natural remedies tailored to your symptoms, body type, and wellness needs.
</p>

<hr style='border: 1px solid #ccc; margin: 20px 0;'>

### 🌿 What This App Does
- 🔍 Understands your **symptoms** through natural language input
- 🧘‍♂️ Suggests remedies based on your **Ayurvedic body type** (Vata, Pitta, Kapha)
- 📚 Retrieves relevant advice from an **embedded knowledge base** using AI
- 🔄 Applies a **fallback strategy** to find broader suggestions if specific matches aren’t found

---

### 🧠 Tech Behind the Scenes

This app combines two powerful frameworks:

- **LangChain** — offers **fine-grained control** over prompt templates, vector search, and LLM interaction.
- **LangGraph** — enables **multi-step reasoning** with user-friendly state flow and fallback logic.

Together, they deliver a smart, responsive assistant that balances precision with flexibility.

---

### 🚀 Powered By
- 🧩 `LangChain` & `LangGraph` for orchestration
- 🧠 `OpenAI GPT-4o-mini` for intelligent response generation
- 🗂️ `FAISS` for fast similarity search over documents
- 📄 `PDFPlumber` for structured PDF content extraction

---

> ⚠️ **Disclaimer**  
> This app is a non-commercial, personal project developed for experimental and educational purposes only, and **not intended for public use**.  
> It uses **sample text** inspired by Ayurvedic principles and is **not created by a certified or trained Ayurvedic practitioner**.  
> The remedies and outputs generated by this tool should **not be considered medical advice**.  
> Always consult a qualified healthcare professional before making any health-related decisions.  
> Use of this content is at your own risk and discretion.
""", unsafe_allow_html=True)
#endregion
